import type { Metadata } from "next";
import localFont         from "next/font/local";
import { Suspense }      from "react";
import "./globals.css";
import { AuthProvider }  from "@/app/context/AuthContext";

const geistSans = localFont({
  src: [
    { path: "../public/fonts/Geist-Regular.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/Geist-Bold.ttf",    weight: "700", style: "normal" },
  ],
  variable: "--font-geist-sans",
  display:  "swap",
});

const geistMono = localFont({
  src: [
    { path: "../public/fonts/GeistMono-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-geist-mono",
  display:  "swap",
});

export const metadata: Metadata = {
  title:       "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}